baseURL = "https://www.greiberheating.com/"
languageCode = "en-us"
title = "Greiber Heating & Sheet Metal"
enableRobotsTXT = true
disableAliases = true
summaryLength = 30

#################### default parameters ################################

[params]
  logo = "/images/Greiber-Heating-Logo.png"
  # Meta data
  description = " "
  author = "Greiber Heating & Sheet Metal"
  # Contact Information
  phone = "608-849-4535"
  email = "karen@greiberheating.com"
  address_line_1 = "402 W Main St"
  address_line_2 = "Waunakee, WI 53597"
  google_map_directions = "https://goo.gl/maps/XDuX7spJ38gDigWL7"
  hours = "Mon-Thurs: 7:30am-5pm"
  hoursFri = "Fri: 7:30am-4pm"
  disallowSearchEngines = true
  # Google Analitycs
  googleAnalytics = "G-3C58J7QYR2" # Your ID# search 
  minifyBundles = true

# add redirects/headers
  [outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Products"
    url  = "/products/"
    weight = 2

  [[menu.main]]
    parent = "Products"
    name = "Air Conditioners"
    weight = 1
    url = "/products/air-conditioners/"

  [[menu.main]]
    parent = "Products"
    name = "Furnaces"
    weight = 2
    url = "/products/furnaces/"

  [[menu.main]]
    parent = "Products"
    name = "Heat Pumps"
    weight = 3
    url = "/products/heat-pumps/"

  [[menu.main]]
    parent = "Products"
    name = "Ductless Systems"
    weight = 4
    url = "/products/ductless-systems/"

  [[menu.main]]
    parent = "Products"
    name = "Smart Thermostats"
    weight = 5
    url = "/products/smart-thermostats/"

  [[menu.main]]
    parent = "Products"
    name = "Evaporator Coils"
    weight = 6
    url = "/products/evaporator-coils/"

  [[menu.main]]
    parent = "Products"
    name = "Boilers"
    weight = 7
    url = "/products/boilers/"

  [[menu.main]]
    parent = "Products"
    name = "Garage Heaters"
    weight = 8
    url = "/products/garage-heaters/"

  [[menu.main]]
    parent = "Products"
    name = "Fan Coils"
    weight = 9
    url = "/products/fan-coils/"

  [[menu.main]]
    parent = "Products"
    name = "Indoor Air Quality"
    weight = 10
    url = "/products/indoor-air-quality/"

[[menu.main]]
    name = "Financing"
    url  = "/financing/"
    weight = 3

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 4

[[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 5

  [[menu.main]]
    parent = "Services"
    name = "Residential Heating Services"
    weight = 1
    url = "/services/residential-heating/"

  [[menu.main]]
    parent = "Services"
    name = "Residential Cooling Services"
    weight = 2
    url = "/services/residential-cooling/"

  [[menu.main]]
    parent = "Services"
    name = "Indoor Air Quality Services"
    weight = 3
    url = "/services/indoor-air-quality-services/"

  [[menu.main]]
    parent = "Services"
    name = "Ductless Split Systems"
    weight = 4
    url = "/services/ductless-split-systems/"

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6

[social]
  facebook = "https://www.facebook.com/GreiberHeatingandSheetMetal/"