baseURL = "/"
languageCode = "en-us"
title = "Greiber Heating & Sheet Metal"
enableRobotsTXT = true
disableAliases = true
summaryLength = 30

#################### default parameters ################################

[params]
  logo = "/images/Greiber-Heating-Logo.jpg"
  # Meta data
  description = " "
  author = "Greiber Heating & Sheet Metal"
  # Contact Information
  phone = "608-849-4535"
  email = "karen@greiberheating.com"
  address = """
    402 W Main St
    Waunakee, WI 53597"""
  GoogleMapDirections = "https://goo.gl/maps/XDuX7spJ38gDigWL7"
  hours = "Mon-Thu: 7:30am-5pm"
  hoursFri = "Fri: 7:30am-4am"
  disallowSearchEngines = true
  # Google Analitycs
  googleAnalytics = " " # Your ID# search 
  minifyBundles = true

# add redirects/headers
  [outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Products"
    url  = "/products/"
    weight = 2

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 3

[[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

[social]
  facebook = "https://www.facebook.com/GreiberHeatingandSheetMetal/"